// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxv8BjaeG5X_xeNkaLN32KM97BBptBVKg',
    appId: '1:549730627206:web:ac5a47dc9b4b01071c2b07',
    messagingSenderId: '549730627206',
    projectId: 'weconnect-3d518',
    authDomain: 'weconnect-3d518.firebaseapp.com',
    storageBucket: 'weconnect-3d518.appspot.com',
    measurementId: 'G-0CBBBQZE76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJQoOtcUaE4vCkx6o_D6xXqvtJxfdDzZo',
    appId: '1:549730627206:android:f10bb924f000f8981c2b07',
    messagingSenderId: '549730627206',
    projectId: 'weconnect-3d518',
    storageBucket: 'weconnect-3d518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlCdUBFxgiR2t6Q1eIPzmRi2WBRN0OPhk',
    appId: '1:549730627206:ios:a1158cecea9935f41c2b07',
    messagingSenderId: '549730627206',
    projectId: 'weconnect-3d518',
    storageBucket: 'weconnect-3d518.appspot.com',
    iosClientId: '549730627206-3eiiijsubnv5eik4m2k5ln2ddi8bj3b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.weconnectPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlCdUBFxgiR2t6Q1eIPzmRi2WBRN0OPhk',
    appId: '1:549730627206:ios:a1158cecea9935f41c2b07',
    messagingSenderId: '549730627206',
    projectId: 'weconnect-3d518',
    storageBucket: 'weconnect-3d518.appspot.com',
    iosClientId: '549730627206-3eiiijsubnv5eik4m2k5ln2ddi8bj3b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.weconnectPortal',
  );
}
